{
    'name': "Dental Hospital Management",
    'description': """
        Hospital management module which is used to mange the hospital functionalities prescription,patient,doctor diagnosis etc
    """,
    'summary': """
    Hospital management module which is used to mange the hospital functionalities prescription,patient,doctor diagnosis etc
""",
    'author': "Alan Technologies",
    'company': "Alan Technologies",
    'maintainer': 'Alan Technologies',
    'website': "https://www.alantech.com",
    "license": "AGPL-3",
    'category': 'Hospital',
    'version': '18.0.1.0.0',
    'depends': ['base', 'hr', 'account', 'sale_management','purchase' ,'product', 'web','stock','mail','contacts'],
    'data': [
        'data/patient_id_sequence.xml',
        'data/dental_specialist_data.xml',
        'data/treatment_category_data.xml',
        'data/dental_treatment_data.xml',
        'data/dental_time_shift_data.xml',
        'data/medicine_frequency_data.xml',
        'data/medicine_data.xml',
        'data/uom_data.xml',
        'data/mail_teamplate.xml',
        'wizard/treatment_report_wizard_view.xml',
        'wizard/doctor_report_wizard_view.xml',
        'wizard/patient_report_wizard_view.xml',
        'views/patient_view.xml',
        'views/dental_appointment_views.xml',
        'views/dental_doctor_views.xml',
        'views/dental_prescription_views.xml',
        'views/dental_payment_log_views.xml',
        'views/teeth_chart_views.xml',
        'views/dental_treatment_views.xml',
        'views/treatment_category_views.xml',
        'views/medicine_frequency_views.xml',
        'views/dental_medicine_views.xml',
        'views/medical_questions_views.xml',
        'views/dental_doctor_views.xml',
        'views/procedure_views.xml',
        'views/dental_specialist_views.xml',
        'views/dental_time_shift_views.xml',
        'views/lab_views.xml',
        'views/dental_diagnosis_views.xml',
        'report/dental_prescription_report.xml',
        'report/dental_prescription_templates.xml',
        'report/custom_report_header.xml',
        'report/patient_history_report.xml',
        'report/report_patient_history.xml',
        'report/doctor_action_report.xml',
        'report/doctor_report_template.xml',
        'report/patient_report_template.xml',
        # 'views/report_menu.xml',
        'report/report_action.xml',
        'report/report_templates.xml',
        'security/ir.model.access.csv',
    ],

    'installable': True,
    'auto_install': True,
    'application': True,

}
